services:
  - type: web
    name: jdmarc-backend
    env: node
    plan: free
    buildCommand: |
      echo "📦 Installing dependencies..."
      npm install

      echo "🧩 Generating Prisma client..."
      npx prisma generate

      echo "🗃️ Pushing Prisma schema to database..."
      npx prisma db push

      echo "🔍 Testing database connection using @prisma/client..."
      node -e "
        import { PrismaClient } from '@prisma/client';
        const prisma = new PrismaClient();
        prisma.$connect()
          .then(() => {
            console.log('✅ Prisma connected successfully!');
            return prisma.$disconnect();
          })
          .catch(err => {
            console.error('❌ Prisma connection failed:', err);
            process.exit(1);
          });
      "

      echo '✅ Build and database check complete!'
    startCommand: npm run start
    autoDeploy: true

    envVars:
      - key: DATABASE_URL
        value: mysql://u158969833_JDM:%3EeH5YG%2AAg@srv1847.hstgr.io:3306/u158969833_Jdm?sslaccept=strict

      - key: DATABASE_SSL
        value: true

      - key: DATABASE_CONNECTION_LIMIT
        value: 10

      - key: NODE_ENV
        value: production

      - key: JWT_SECRET
        generateValue: true

      - key: CORS_ORIGIN
        value: `https://jdmarcng.com`

    healthCheckPath: /api/health
    autoDeployOnGitPush: true