services:
  - type: web
    name: jdmarc-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5004
      - key: CORS_ORIGIN
        value: https://jdmarcng.com
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: BCRYPT_ROUNDS
        value: 12
      - key: API_VERSION
        value: v1
      - key: BASE_URL
        value: https://builder-aura-field.onrender.com
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: FRONTEND_URL
        value: "https://jdmarcng.com"
    healthCheckPath: /api/health