name: Build and Deploy Frontend

on:
  push:
    branches: [main]
    paths-ignore:
      - 'backend/**'
      - '.github/workflows/deploy-to-render.yml'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run type check
      run: npm run typecheck || echo "Type check failed but continuing"
      
    - name: Build application
      run: npm run build
      env:
        VITE_API_URL: https://builder-aura-field.onrender.com/api
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: jdmarcng.com
